name:                vec2words
version:             0.1.0.0
github:              "githubuser/vec2words"
license:             BSD3
author:              "Marwan"
maintainer:          "marwansabih@gmx.de"
copyright:           "BSD"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/vec2words#readme>

dependencies:
- base >= 4.7 && < 5
- ghc-prim
- vector
- time
- random
- directory
- hashmap
- hspec
- QuickCheck

library:
  source-dirs: src

executables:
  vec2words-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - vec2words

tests:
  vec2words-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - vec2words
